# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smallWeightHamiltonianPath <- function(dmat) {
    .Call('epicseg_smallWeightHamiltonianPath', PACKAGE = 'epicseg', dmat)
}

bindCols <- function(vlist, nthreads = 1L) {
    .Call('epicseg_bindCols', PACKAGE = 'epicseg', vlist, nthreads)
}

writeCountsTXT <- function(counts, marks, path) {
    invisible(.Call('epicseg_writeCountsTXT', PACKAGE = 'epicseg', counts, marks, path))
}

avgCountsPerClust <- function(counts, clusts) {
    .Call('epicseg_avgCountsPerClust', PACKAGE = 'epicseg', counts, clusts)
}

colSummary <- function(mat, type, nthreads = 1L) {
    .Call('epicseg_colSummary', PACKAGE = 'epicseg', mat, type, nthreads)
}

getRef <- function(mat, type, nthreads = 1L) {
    .Call('epicseg_getRef', PACKAGE = 'epicseg', mat, type, nthreads)
}

quantileNorm <- function(mat, ref, nthreads = 1L, seed = 13L) {
    .Call('epicseg_quantileNorm', PACKAGE = 'epicseg', mat, ref, nthreads, seed)
}

clist2mlist <- function(clist, nthreads = 1L) {
    .Call('epicseg_clist2mlist', PACKAGE = 'epicseg', clist, nthreads)
}

mlist2clist <- function(mlist, nthreads = 1L) {
    .Call('epicseg_mlist2clist', PACKAGE = 'epicseg', mlist, nthreads)
}

testSortCounts <- function(v) {
    .Call('epicseg_testSortCounts', PACKAGE = 'epicseg', v)
}

testMeanAndMedian <- function(v, type) {
    .Call('epicseg_testMeanAndMedian', PACKAGE = 'epicseg', v, type)
}

statesToSegments_helper <- function(regions, states) {
    .Call('epicseg_statesToSegments_helper', PACKAGE = 'epicseg', regions, states)
}

segmentsToBed <- function(segments, labels, colors, path) {
    invisible(.Call('epicseg_segmentsToBed', PACKAGE = 'epicseg', segments, labels, colors, path))
}

