# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smallWeightHamiltonianPath <- function(dmat) {
    .Call('epicseg_smallWeightHamiltonianPath', PACKAGE = 'epicseg', dmat)
}

bindCols <- function(vlist) {
    .Call('epicseg_bindCols', PACKAGE = 'epicseg', vlist)
}

writeCountsTXT <- function(counts, marks, path) {
    invisible(.Call('epicseg_writeCountsTXT', PACKAGE = 'epicseg', counts, marks, path))
}

avgCountsPerClust <- function(counts, clusts) {
    .Call('epicseg_avgCountsPerClust', PACKAGE = 'epicseg', counts, clusts)
}

statesToSegments_helper <- function(regions, states) {
    .Call('epicseg_statesToSegments_helper', PACKAGE = 'epicseg', regions, states)
}

segmentsToBed <- function(segments, labels, colors, path) {
    invisible(.Call('epicseg_segmentsToBed', PACKAGE = 'epicseg', segments, labels, colors, path))
}

